app/users/forms.py
from flask_wtf import FlaskForm
from flask import flash
import phonenumbers
from wtforms import SubmitField, StringField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length
from wtforms import ValidationError
from ..models import User


class RegistrationForm(FlaskForm):
    """ Registration form that checks for valid username, email and password using the Regexps in order to keep password
    in desirable form , right now its set that username can only contain Letters and numbers it can be changed to more
    complex regex requirement if needed"""
    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                                             Email()])


    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    password = PasswordField("Enter your password", validators=[DataRequired(), \
                                                                EqualTo('pass_confirm', message='Password must match')])

    pass_confirm = PasswordField("Comfirm your password", validators=[DataRequired()])
    city = StringField('City name ', validators=[DataRequired()])
    country = StringField('Country', validators=[DataRequired()])
    company = StringField('Company name')
    phone = StringField('Phone number', validators=[DataRequired()])
    vat = StringField(validators=[DataRequired()])

    submit = SubmitField("Register")

    # Used to check if the user email exists in the current database and returns ValidationEerror in that case
    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            flash('Email already registered')
            raise ValidationError('Email already registered')

    # Used to check if the users username exists in the current database and returns ValidationEerror in that case
    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            flash('Username already taken')
            raise ValidationError('Username already taken')

    def validate_phone(self, phone):
        try:
            p = phonenumbers.parse(phone.data)
            if not phonenumbers.is_valid_number(p):
                raise ValueError()
        except (phonenumbers.phonenumberutil.NumberParseException, ValueError):
            flash('Invalid phone number !')
            raise ValidationError('Invalid phone number')


class LoginForm(FlaskForm):
    email = StringField('Username', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')


class ResetPasswordRequestForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(),
                                                             EqualTo('password')])
    submit = SubmitField('Request Password Reset')

class ResendVerification(FlaskForm):
    submit = SubmitField('Resend Verification Email')

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views, errors

app/users/views.py
from .. import db
from ..models import User
from flask import render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required, login_user, logout_user
from . import users
from .forms import RegistrationForm, LoginForm, ResetPasswordRequestForm, ResetPasswordForm, ResendVerification
from ..email import send_email


@users.route('/register', methods=['POST', 'GET'])
def register():
    """ Simple registration view , using flask_WTF and sending the email to the user with sendGrind in order to
    access they're accounts and proceed with the training scheduling"""

    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, first_name=form.first_name.data, last_name=form.last_name.data, \
                    password=form.password.data, city=form.city.data, country=form.country.data,\
                    company=form.company.data, phone_number=form.phone.data, vat_tax_id=form.vat.data)
        db.session.add(user)
        db.session.commit()
        send_email(user.email, 'Confirm your Account !',
                    'email/register', user=user, token=user.generate_confirm_token())
        flash('You account is successfully created, please check your email and confirm your account')
        return redirect(url_for('users.login'))
    return render_template('users/register.html', form=form)


@users.route('/login', methods=['POST', 'GET'])
def login():
    """Straight forward with this , simple form validation check and redirection to the index page , we use Flask-Login
    next query string argument, which can be accessed from the request.args dictionary.
    If the next query string argument is not available, a redirect to the home page is issued instead."""

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # After querying over users to find the one with username from form we use verify_password method to check
        # if password was correct and then proceed to log user in .
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            flash('You are logged in')
            next = request.args.get('next')
            if next is None or not next.startswith('/'):
                next = url_for('core.index')
            return redirect(next)
        flash('Wrong username or password')

    return render_template('users/login.html', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You have logged out")
    return redirect(url_for(('core.index')))


@users.route('/confirm/<token>')
@login_required
def confirm(token):
    """ After the user recieve  the email up on clicking the link he will be redirected here note all that confirmation
    work is already done inside the user Model and we just commit the changes up inside the view if they pass the confirm
    method."""
    if current_user.confirmed:
        return redirect(url_for('core.index'))

    if current_user.confirm(token):
        db.session.commit()
        flash("You have confirmed your account")
    else:
        flash("The confirmation link is invalid or has expired.")

    return redirect(url_for('core.index'))


@users.route('/reset_password_request', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_email(user.email, 'Reset Your password!',
                       'email/reset_password', user=user, token=user.generate_password_reset_token())
        flash('Check your email for the instructions to reset your password')
        return redirect(url_for('users.login'))
    return render_template('users/reset_password_request.html', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    """  After the user clicks on the link in email we use @staticmethod from user model which reads the data in token
    data in token is the users id , i do the query over the model and return that user model and proceed to use
    set_password method to change the password """

    if current_user.is_authenticated:
        return redirect(url_for('core.index'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('core.index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('users.login'))
    return render_template('users/resetpassword.html', form=form)


@users.route('/verify_resend', methods=['GET', 'POST'])
def verify_resend():
    form = ResendVerification()

    if form.validate_on_submit():
        send_email(current_user.email, 'Confirm your Account !',
                   'email/register', user=current_user, token=current_user.generate_confirm_token())
        flash('Verification email has been sent, check your inbox for instructions !')

        return redirect(url_for('core.index'))

    return render_template('users/resend_verify.html', form=form)

app/templates/users/login.html
{% extends 'base.html' %}
{% block head %}
{{ super () }}
<style>
    footer{
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<section class="min-vh-100">
<div class="container">
    <div class="row ">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5 " >
                <div class="card-body">
                    <h5 class="card-title text-center">Sign In</h5>
                    <form method="POST">
                        {{ form.hidden_tag() }}
                        <div class="form-label-group">
                            {{ form.email.label }}
                            {{ form.email(class='form-control', placeholder='Username') }}
                        </div>
                        <div class="form-label-group">
                            {{ form.password.label }}
                            {{ form.password(class='form-control', placeholder='Password') }}
                        </div>
                        {{ form.submit( class='btn btn-primary mt-4' )}}
                        <div class="row justify-content-start mt-4">
                            <hr class="my-4">
                            <div class="col">
                               <a href="{{ url_for('users.reset_password_request') }}"> <span>Forgot your password ?</span></a>
                            </div>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
    <hr>
    <div class="col text-center">
        <a class="btn" href="{{ url_for('core.contact_us') }}">Contact Us</a>
    </div>
</div>
</section>
{% endblock %}

app/templates/users/register.html
{% extends 'base.html' %}
{% block head %}
{{ super () }}
<style>
@media only screen and (max-width: 768px) {
	footer{
        position: fixed;
        bottom: 0;
    }
    .btn{
        margin-bottom: 5rem;
    }
}
</style>
{% endblock %}

{% block content %}
<section class="min-vh-100">
    <div class="container">
        <div class="card">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-8 col-xl-6">
                <div class="row">
                    <div class="col text-center">
                        <h1>Register</h1>
                        <p class="text-h3">Welcome dear visitor in order to see training catalogue please take your time and register on our web page </p>
                    </div>
                </div>
                <form method="POST">
                  {{ form.hidden_tag() }}
                <div class="row align-items-center mt-4">
                    <div class="col">
                        {{ form.first_name(class='form-control', placeholder='First Name')}}
                    </div>
                    <div class="col">
                        {{ form.last_name(class='form-control', placeholder='Last name')}}
                    </div>
                </div>
                        <div class="row align-items-center mt-4">
                    <div class="col">
                        {{ form.email(class='form-control', placeholder='Email')}}
                    </div>
                </div>

                <div class="row align-items-center mt-4">
                    <div class="col">
                        {{ form.password(class='form-control', placeholder='Password')}}
                    </div>
                    <div class="col">
                        {{ form.pass_confirm(class='form-control', placeholder='Confirm Password')}}
                    </div>
                </div>
                    <div class="row align-items-center mt-4">
                    <div class="col">
                        {{ form.city(class='form-control', placeholder='City')}}
                    </div>
                    <div class="col">
                        {{ form.country(class='form-control', placeholder='Country')}}
                    </div>
                    </div>
                    <div class="row align-items-center mt-4">
                    <div class="col-6">
                        {{ form.company(class='form-control', placeholder='Company Name')}}
                    </div>
                    <div class="col">
                        {{ form.phone(class='form-control', id='phone' ) }}
                    </div>
                    </div>
                      <div class="row align-items-center mt-4">
                    <div class="col">
                        {{ form.vat(class='form-control', placeholder="VAT / Tax ID") }}
                    </div>
                      </div>
                    <div class="col mb-5 text-center">
                        {{ form.submit( class='btn btn-dark mt-4' )}}
                         </form>
                        </div>
            </div>
         </div>
       </div>
    <div class="row">
        <div class="col-12 col-sm-6 col-md-6 col-lg-6 text-center">
            <h1> Having troubles ? </h1>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus consectetur corporis deleniti deserunt dignissimos ea praesentium! Ab beatae facilis minima minus non odit quam quod voluptate. Dolore et nisi sed.</span>
            </p>
            <a class="btn" href="{{url_for('core.contact_us')}}">Contact us</a>
            <hr>
        </div>
        <div class="col-12 col-sm-6 col-md-6 col-lg-6 text-center">
            <h1>Already have an account ?</h1>
            <p>
                <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi autem dolorem optio tempora. Consequuntur, distinctio, quod. A asperiores, commodi, consequatur cumque debitis, id magni nam nisi possimus repellat ut veniam!</span>
            </p>
            <a class="btn" href="{{url_for('users.login')}}">Log In</a>
            <hr>
        </div>
    </div>
</div>
</section>


{% block scripts %}
<script>
    $(document).ready(function () {
        var wtf_phone_field = document.getElementById('phone');
        wtf_phone_field.style.position = 'absolute';
        wtf_phone_field.style.top = '-9999px';
        wtf_phone_field.style.left = '-9999px';
        wtf_phone_field.parentElement.insertAdjacentHTML('beforeend', '<div><input class="col" type="tel" id="_phone"></div>');
        var fancy_phone_field = document.getElementById('_phone');
        var fancy_phone_iti = window.intlTelInput(fancy_phone_field, {
            separateDialCode: true,
            utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.0/js/utils.js",

        });
        fancy_phone_iti.setNumber(wtf_phone_field.value);
        fancy_phone_field.addEventListener('blur', function () {
            wtf_phone_field.value = fancy_phone_iti.getNumber();
        });
    });
</script>
{% endblock %}
{% endblock %}

app/templates/users/resend_verify.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="vh-100 container">
        <h1 class="text-center">Verification</h1>
        <hr>
        <div class="d-flex justify-content-center">
            <ion-icon name="book-outline" size="large"></ion-icon>
        </div>
            <div class="d-flex justify-content-center">
                <p><span> Up on registration you have receive an email with instructions how to verify your email , please check your inbox !</span>
                </p>
            </div>
            <div class="d-flex justify-content-center">
                <p><span>Your verification cod expired ? Please click on button below in order to receive verification email</span>
                </p>
            </div>
        <div class="d-flex justify-content-center">
            <form method="POST">
            {{ form.hidden_tag () }}
            <div class="col">
            {{ form.submit(class='btn form-control') }}
            </div>
            </form>
        </div>
        </div>
{% endblock %}

app/templates/users/reset_password_request.html
{% extends 'base.html' %}
{% block head %}
{{ super () }}
<style>
    footer{
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Sign In</h5>
                    <form method="POST">
                        {{ form.hidden_tag() }}
                        <div class="form-label-group">
                            {{ form.email.label }}
                            {{ form.email(class='form-control', placeholder='Email') }}
                        </div>
                        {{ form.submit( class='btn btn-primary mt-4' )}}
                        <div class="row justify-content-start mt-4">
                            <hr class="my-4">
                            <div class="col">
                                <span>Proceed to enter you email address in order to reset your password</span>
                            </div>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

app/templates/users/resetpassword.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Sign In</h5>
                    <form method="POST">
                        {{ form.hidden_tag() }}
                        <div class="form-label-group">
                            {{ form.password.label }}
                            {{ form.password(class='form-control', placeholder='Password') }}
                        </div>

                        <div class="form-label-group">
                            {{ form.password2.label }}
                            {{ form.password2(class='form-control', placeholder='Repeat Password') }}
                        </div>
                        {{ form.submit( class='btn btn-primary mt-4' )}}
                        <div class="row justify-content-start mt-4">
                            <hr class="my-4">
                            <div class="col">
                                <span>Proceed to enter you email address in order to reset your password</span>
                            </div>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}